homework/blog/urls.py
from django.urls import path

from .views import product_detail, home_page, create_product, get_product_by_tag

app_name = "blog"

urlpatterns = [
    path('home/', home_page, name='home'),
    path("products/<int:product_id>", product_detail, name="product_detail"),
    path("create_product/", create_product, name="create_product"),
     path('tags/<int:tag_id>/', get_product_by_tag, name='get_product_by_tag'),
]

homework/homework/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls", namespace='blog'))
]

homework/blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField()
    added_at = models.DateTimeField(auto_now_add=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="products")
    tags = models.ManyToManyField(Tag, related_name="products")

    def get_absolute_url(self):
        return reverse('blog:product_detail', args=[self.id])
    

homework/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages

from .models import Product, User, Tag


def home_page(request):
    products = Product.objects.all()
    return render(request, "index.html", {"products": products})


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)  
    if request.method == "POST":
        product.delete()
        messages.success(request, f"Product '{product.name}' deleted !")
        return redirect("blog:home")
    return render(request, "product_info.html", {"product": product})\
    

def create_product(request):
    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")
        price = float(request.POST.get("price")) 
        seller = get_object_or_404(User, id=1)  
        
        try:
            product = Product(name=name, description=description, price=price, seller=seller)
            product.full_clean()
        except Exception as e:
            return HttpResponse(f"<h1>Invalid Data: {e}</h1>")

        else:
            product.save()
            tags_id = request.POST.getlist("tags")
            tags = Tag.objects.filter(id__in=tags_id) 
            product.tags.set(tags)
            return redirect("blog:home") 

    tags = Tag.objects.all()
    return render(request, "create_product.html", {"tags": tags})


def get_product_by_tag(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id)
    products = Product.objects.filter(tags=tag)
    data = {
        "tag": tag,
        "products": products
    }
    return render(request, "product_by_tag.html", data)

homework/blog/templates/__base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>My site</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

homework/blog/templates/create_product.html
{% extends '__base.html' %}

{% block content %}
    <h1>Create New Product</h1>

    <form action="{% url 'blog:create_product' %}" method="post">
        {% csrf_token %}
        
        <label class="form-label">Title</label>
        <input type="text" name="name" class="form-control" required/>
        
        <label class="form-label">Description</label>
        <textarea name="description" class="form-control" required></textarea>
        
        <label class="form-label">Price</label>
        <input type="number" name="price" class="form-control" step="0.01" min="0" required/>
        
        <label class="form-label">Tags</label>
        <div>
            {% for tag in tags %}
                <div>
                    <label>
                        <input type="checkbox" name="tags" value="{{ tag.id }}" /> {{ tag.name }}
                    </label>
                </div>
            {% endfor %}
        </div>
        
        <button type="submit">Create</button>
    </form>
    
{% endblock %}

homework/blog/templates/index.html
{% extends '__base.html' %}

{% block content %}
<div class="container my-4">
  <h1 class="text-center mb-3">Main Page</h1>

  <div class="mb-3">
    <a href="{% url 'blog:create_product' %}" class="btn btn-primary">Create Product</a>
  </div>

  {% if messages %}
  <div class="mt-3">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <h3 class="border-bottom pb-2">All Products</h3>
  <div class="row row-cols-2 g-4">
    {% for product in products %}
    <div class="col">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <h4 class="card-title">{{ product.name }}</h4>
        </div>
        <div class="card-footer text-end">
          <a href="{{ product.get_absolute_url }}" class="btn btn-outline-primary">Info</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

homework/blog/templates/product_by_tag.html
{% extends '__base.html' %}

{% block content %}
    <h1>Products tagged with "{{ tag.name }}"</h1>

    <h3>List of Products:</h3>
    <ul>
        {% if products %}
            {% for product in products %}
                <li>
                    <a href="{% url 'blog:product_detail' product.id %}">{{ product.name }}</a> 
                    - {{ product.price }} 
                    <p>{{ product.description }}</p>
                </li>
            {% endfor %}
        {% else %}
            <p>No products found for this tag.</p>
        {% endif %}
    </ul>
{% endblock %}

homework/blog/templates/product_info.html
{% extends '__base.html' %}

{% block content %}
<div>
    <p>{{ product.name }}</p>
    <p>{{ product.description }}</p>
    <p>{{ product.price }}</p>

    <h3>Tags:</h3>
    <ul>
        {% for tag in product.tags.all %}
            <li>
                <a href="{% url 'blog:get_product_by_tag' tag.id %}">{{ tag.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

<form action="{% url 'blog:product_detail' product.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

{% endblock %}